### ISSUE TITLE
got New Issue on Autodl

### ISSUE THREAD

**Issue by kishan167** [autodl-community/autodl-irssi#213]
**Please read the contributing guidelines linked above before opening an issue.**
hi there

im getting new Error on Rtorrent from Autodl

autodl-irssi: __init2: ex: Exception info: No content elem with id autodl-prefs-contents-upload

**Comment by illnesse** [comment]
yeah might be due to the jquery update in rutorrent?

**Comment by kishan167** [comment]
it happened only today with fresh install of swizzin my other server running fine on it

**Comment by brettpetch** [comment]
@kishan167 @illnesse I can confirm it's due to the recent rutorrent updates with jquery. You can revert to the last known good commit by doing 

```bash
sudo git -C /srv/rutorrent/ checkout 6bffcb1d3fd0a25dcba9100a6bbbc6cb8de7af29
```

/b

**Comment by sk1llsh0t** [comment]
i'm getting this same issue. any word on getting this working again with the latest rutorrent version?

**Comment by A69Tor** [comment]
Any update? Experiencing this issue as well

**Comment by sk1llsh0t** [comment]
Was this fixed in a particular commit? Why was this issue closed?

**Comment by A69Tor** [comment]
> Was this fixed in a particular commit? Why was this issue closed?

Probably closed because he didn't want to get updates anymore. This issue is not resolved though at all.

**Comment by albertusQuelle** [comment]
Still open
